# -*- coding: utf-8 -*-

from . import class_model
from . import room
from . import insurance
from . import patient
from . import res_partner
from . import doctor
from . import product
from . import sale_order
from . import concoction
from . import prescription
from . import owlexa
from . import account_invoice
from . import registration
from . import unit_registration
from . import unit_registration_action
from . import appointment
from . import diagnostic
from . import medical_evaluation
from . import lab
from . import stock_operation_pack
from . import stock_scrap
from . import jakc_queue
from . import res_users
from . import purchase_order
from . import pengkajian_rawat_jalan_report
from . import medical_physician
from . import operating_unit
